Models/ErrorViewModel.cs
namespace WebApplication10.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Marca.cs
namespace WebApplication10.Models
{
    public class Marca
    {
        public int codigo { get; set; }
        public string nome { get; set; }

        internal List<Marca> toList()
        {
            throw new NotImplementedException();
        }
    }

    public class MarcaViewModel
    {
        public List<Marca> Marcas { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public string SearchTerm { get; set; }
    }
}

Models/Modelos.cs
using WebApplication10.Singletons;

namespace WebApplication10.Models
{
    public class Modelos
    {
        public List<Modelo> modelos { get; set; }
        public List<Ano> anos { get; set; }
    }

    public class Modelo
    {
        public int codigo { get; set; }
        public string nome { get; set; }
    }

    public class Ano
    {
        public string codigo { get; set; }
        public string nome { get; set; }
    }


    public class ModelosModel
    {
        public List<Modelo> Modelos { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public string SearchTerm { get; set; }
        public string nomeMarca { get; internal set; }
        public string marcaCodigo { get; internal set; }
    }
}

Models/Veiculo.cs
namespace WebApplication10.Models
{
    public class Veiculo
    {
        public int TipoVeiculo { get; set; }
        public string Valor { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int AnoModelo { get; set; }
        public string Combustivel { get; set; }
        public string CodigoFipe { get; set; }
        public string MesReferencia { get; set; }
        public string SiglaCombustivel { get; set; }
    }
}

Models/Versoes.cs
namespace WebApplication10.Models
{
    public class Versoes
    {
        public string codigo { get; set; }
        public string nome { get; set; }
    }

    internal class VersoesModel
    {
        public List<Versoes> Versoes { get; set; }
        public string NomeModelo { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public string SearchTerm { get; set; }
        public string marcaId { get; internal set; }
        public string modeloId { get; internal set; }
    }
}

Controllers/AnoVeiculoController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication10.Models;
using WebApplication10.Services;
using WebApplication10.Singletons;

namespace WebApplication10.Controllers
{
    public class AnoVeiculoController : Controller
    {
        private readonly ConsumoApi _client;
        private readonly ModeloGlobalNome _modeloNome;
        private readonly ModeloGlobalValue _modeloCodigo;

        public AnoVeiculoController(ModeloGlobalNome modeloNome, ModeloGlobalValue modeloCodigo)
        {
            _modeloNome = modeloNome;
            _modeloCodigo = modeloCodigo;
            _client = new ConsumoApi();
        }

        public async Task<IActionResult> AnoVeiculoSearch(string id, string nomeModelo,string marca, string searchTerm, int page = 1)
        {
            if (!string.IsNullOrEmpty(id))
            {
                if (_modeloCodigo.GetValue() != id)
                {
                    _modeloCodigo.SetValue(id);
                }
            }

            if (!string.IsNullOrEmpty(nomeModelo))
            {
                if (_modeloNome.GetValue() != nomeModelo)
                {
                    _modeloNome.SetValue(nomeModelo);
                }
            }

            int pageSize = 12;

            var Versao = await _client.GetVersoesAsync(marca, _modeloCodigo.GetValue());

            if (!string.IsNullOrEmpty(searchTerm))
            {
                Versao = Versao.Where(m => m.nome.Contains(searchTerm, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            if (Versao == null)
            {
                return NotFound();
            }

            int totalModelos = Versao.Count();

            var detalhesViewModel = new VersoesModel
            {
                marcaId = marca,
                modeloId = _modeloCodigo.GetValue(),
                Versoes = Versao,
                NomeModelo = _modeloNome.GetValue(),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(totalModelos / (double)pageSize),
                SearchTerm = searchTerm
            };

            return PartialView("_Versoes", detalhesViewModel);
        }
    }
}

Controllers/FipeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication10.Models;
using WebApplication10.Services;
using WebApplication10.Singletons;

namespace WebApplication10.Controllers
{
    public class FipeController : Controller
    {
        private readonly ConsumoApi _client;
        private readonly versaoGlobalNome _modeloNome;
        private readonly ModeloGlobalValue _modeloCodigo;

        public FipeController(versaoGlobalNome modeloNome, ModeloGlobalValue modeloCodigo)
        {
            _modeloNome = modeloNome;
            _modeloCodigo = modeloCodigo;
            _client = new ConsumoApi();
        }

        public async Task<IActionResult> SerachFipe(string id, string modelo, string marca)
        {

            var Versao = await _client.GetVeiculoAsync(marca, modelo, id);

            return PartialView("_Veiculo", Versao);
        }
    }
}

Controllers/MModelosController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication10.Models;
using WebApplication10.Services;
using WebApplication10.Singletons;

namespace WebApplication10.Controllers
{
    public class MModelosController : Controller
    {
        private readonly ConsumoApi _client;
        private readonly MarcaGlobalValue _marca;
        private readonly MarcaGlobalNome nomeMarcapro;
        public MModelosController(MarcaGlobalValue marca, MarcaGlobalNome nomeMarcapro)
        {
            _client = new ConsumoApi();
            _marca = marca;
            this.nomeMarcapro = nomeMarcapro;

        }

        public async Task<IActionResult> Search(string id,string nomeMarca, string searchTerm, int page = 1)
        {
            if (!string.IsNullOrEmpty(id))
            {
                if (_marca.GetValue() != id)
                {
                    _marca.SetValue(id);
                }
            }

            if(!string.IsNullOrEmpty(nomeMarca)) {
                if (nomeMarcapro.GetValue() != nomeMarca)
                {
                    nomeMarcapro.SetValue(nomeMarca);
                }
            }

            int pageSize = 12;
            var marca = await _client.GetModelosAsync(_marca.GetValue().ToString());
            var modelos = new List<Modelo>();
            modelos = marca.modelos;

            if (!string.IsNullOrEmpty(searchTerm))
            {
                modelos = modelos.Where(m => m.nome.Contains(searchTerm, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            if (modelos == null)
            {
                return NotFound();
            }

            int totalModelos = modelos.Count();

            var detalhesViewModel = new ModelosModel
            {
                marcaCodigo = _marca.GetValue(),
                Modelos = modelos,
                nomeMarca = nomeMarcapro.GetValue(),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(totalModelos / (double)pageSize),
                SearchTerm = searchTerm
            };

            return PartialView("_Modelo", detalhesViewModel);
        }
    }
}

Views/AnoVeiculo/_Versoes.cshtml
@model VersoesModel

<div class="row">
    <div class="text-center">
        <h3>Versoes Disponiveis: @Model.NomeModelo</h3>
    </div>
    <br />
    @if (Model.Versoes.Count > 0)
    {
        @foreach (var versao in Model.Versoes)
        {
            <div class="col-md-3 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@versao.nome</h5>
                        <p class="card-text">Código: @versao.codigo</p>
                        <button type="button" class="btn-success"
                                data-toggle="modal"
                                data-target="#Fipe"
                                data-id="@versao.codigo"
                                data-marca="@Model.marcaId"
                                data-modelo="@Model.modeloId"
                                data-nome="@versao.nome"
                                onclick="showFipe(event)">
                            Ver Detalhes
                        </button>
                    </div>
                </div>
            </div>
        }
    }
</div>
<div class="row">
    <div class="col-md-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @if (Model.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@(Model.CurrentPage - 1))">Previous</a>
                    </li>
                }
                @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@i)">@i</a>
                    </li>
                }
                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@(Model.CurrentPage + 1))">Next</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

Views/Fipe/_Veiculo.cshtml
@model Veiculo
<div class="card m-3">
    <div class="card-body">
        <p><strong>Tipo de Veículo:</strong> @Model.TipoVeiculo</p>
        <p><strong>Valor:</strong> @Model.Valor</p>
        <p><strong>Marca:</strong> @Model.Marca</p>
        <p><strong>Modelo:</strong> @Model.Modelo</p>
        <p><strong>Ano do Modelo:</strong> @Model.AnoModelo</p>
        <p><strong>Combustível:</strong> @Model.Combustivel</p>
        <p><strong>Código FIPE:</strong> @Model.CodigoFipe</p>
        <p><strong>Mês de Referência:</strong> @Model.MesReferencia</p>
        <p><strong>Sigla do Combustível:</strong> @Model.SiglaCombustivel</p>
    </div>
</div>

Views/Home/Index.cshtml
@model MarcaViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row m-5">
        <div class="col-md-12">
            <input type="text" id="searchTerm" class="form-control" placeholder="Search for a brand" onkeyup="searchBrands()">
        </div>
    </div>
    <br />
    <div id="marcaList">
        @Html.Partial("_MarcaList", Model)
    </div>
    <br />
    <div class="m-5" id="modelos" hidden>
        <div class="col-md-12 m-5">
            <input type="text" id="modelSearchTerm" class="form-control" placeholder="Search for a Model" onkeyup="searchModels()">
        </div>
        <div id="ModelList"></div>
    </div>

    <div class="m-5" id="AnoVeiculo" hidden>
        <div id="AnoVeiculoList"></div>
    </div>

    <div class="m-5" id="Fipe" hidden>

    </div>

</div>


@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>

        function searchBrands() {
            var searchTerm = $('#searchTerm').val();
            $.ajax({
                url: '@Url.Action("Search", "Home")',
                data: { searchTerm: searchTerm },
                success: function (data) {
                    $('#marcaList').html(data);
                }
            });
        }

        function loadPage(page) {
            var searchTerm = $('#searchTerm').val();
            $.ajax({
                url: '@Url.Action("Search", "Home")',
                data: { searchTerm: searchTerm, page: page },
                success: function (data) {
                    $('#marcaList').html(data);
                }
            });
        }

        function searchModels() {
            var searchTerm = $('#modelSearchTerm').val();
            $.ajax({
                url: '@Url.Action("Search", "MModelos")',
                data: { searchTerm: searchTerm },
                success: function (data) {
                    $('#ModelList').html(data);
                }
            });
        }

        function showModal(event) {
            console.log("Clicou em detalhes");
            // Recupera o botão que chamou o modal
            var button = $(event.currentTarget);
            var marcaId = button.data("id");
            marcaIdG = marcaId;
            var marcaNome = button.data("nome");
            var target = button.data('target');
            // Define os dados no modal
            var modal = $('#modelos');
            modal.find('.modal-title').text('Modelos: ' + marcaNome);
            modal.find('.modal-body').text('Carregando detalhes...');
            // Faz a requisição AJAX para obter os modelos da marca
            $.ajax({
                url: '@Url.Action("Search", "MModelos")',
                data: { id: marcaIdG, nomeMarca: marcaNome },
                success: function (data) {
                    $("#modelos").removeAttr('hidden');
                    $('#ModelList').html(data);

                    $('html, body').animate({
                        scrollTop: $(target).offset().top
                    }, 1000);

                },
                error: function () {
                    $("#modelos").attr('hidden', 'hidden');
                }
            });
        }


        function showVersoes(event) {

            // Recupera o botão que chamou o modal
            var button = $(event.currentTarget);
            var versaoId = button.data("id");
            var marcaCodigo = button.data("marca")
            versaoIdG = versaoId;
            var versaoNome = button.data("nome");
            var target = button.data('target');
            // Define os dados no modal

            // Faz a requisição AJAX para obter os modelos da versao
            $.ajax({
                url: '@Url.Action("AnoVeiculoSearch", "AnoVeiculo")',
                data: { id: versaoIdG, nomeModelo: versaoNome, marca: marcaCodigo },
                success: function (data) {
                    $("#AnoVeiculo").removeAttr('hidden');
                    $('#AnoVeiculoList').html(data);

                    $('html, body').animate({
                        scrollTop: $(target).offset().top
                    }, 1000);

                },
                error: function (error) {
                    $("#AnoVeiculo").attr('hidden', 'hidden');

                }
            });
        }

        //showFipe

        function showFipe(event) {

            // Recupera o botão que chamou o modal
            var button = $(event.currentTarget);
            var versaoId = button.data("id");
            var marcaCodigo = button.data("marca")
            var modeloCodigo = button.data("modelo")
            versaoIdG = versaoId;
            var versaoNome = button.data("nome");
            var target = button.data('target');
            // Define os dados no modal

            // Faz a requisição AJAX para obter os modelos da versao
            $.ajax({
                url: '@Url.Action("SerachFipe", "Fipe")',
                data: { id: versaoIdG, modelo: modeloCodigo, marca: marcaCodigo },
                success: function (data) {
                    $("#Fipe").removeAttr('hidden');
                    $('#Fipe').html(data);

                    $('html, body').animate({
                        scrollTop: $(target).offset().top
                    }, 1000);

                },
                error: function (error) {
                    //$("#Fipe").attr('hidden', 'hidden');
                    console.log(error);

                }
            });
        }
                
    </script>
}

Views/Home/_MarcaList.cshtml
@model MarcaViewModel

<div class="row">
    @foreach (var marca in Model.Marcas)
    {
        <div class="col-md-3 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@marca.nome</h5>
                    <p class="card-text">Código: @marca.codigo</p>
                    <button type="button" class="btn btn-primary"
                            data-toggle="modal"
                            data-target="#modelos"
                            data-id="@marca.codigo"
                            data-nome="@marca.nome"
                            onclick="showModal(event)">
                        Ver Detalhes
                    </button>
                </div>
            </div>
        </div>
    }
</div>

<div class="row">
    <div class="col-md-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @if (Model.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@(Model.CurrentPage - 1))">Previous</a>
                    </li>
                }
                @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@i)">@i</a>
                    </li>
                }
                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@(Model.CurrentPage + 1))">Next</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

Views/MModelos/_Modelo.cshtml
@model ModelosModel

<div class="row">
    <div class="text-center">
        <h3>Modelos Disponiveis: @Model.nomeMarca</h3>
    </div>
    <br />
    @if(Model.Modelos.Count > 0){
        @foreach (var modelo in Model.Modelos)
        {
            <div class="col-md-3 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@modelo.nome</h5>
                        <p class="card-text">Código: @modelo.codigo</p>
                        <button type="button" class="btn btn-primary"
                                data-toggle="modal"
                                data-target="#AnoVeiculo"
                                data-id="@modelo.codigo"
                                data-nome="@modelo.nome"
                                data-marca="@Model.marcaCodigo"
                                onclick="showVersoes(event)">
                            Ver Detalhes
                        </button>
                    </div>
                </div>
            </div>
        }
    }
</div>
<div class="row">
    <div class="col-md-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @if (Model.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@(Model.CurrentPage - 1))">Previous</a>
                    </li>
                }
                @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@i)">@i</a>
                    </li>
                }
                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);" onclick="loadPage(@(Model.CurrentPage + 1))">Next</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication10</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>